#!/bin/sh -e

# Source debconf library.
. /usr/share/debconf/confmodule

db_progress START 0 1 pingcheck/note

if ! wget -q -O /dev/null http://www.google.com; then
    db_input critical pingcheck/error || true
    db_go
else
    db_progress STEP 1
fi

db_progress STOP
